### ISSUE TITLE
win10 1803版本

### ISSUE THREAD

**Issue by QAQLC** [Zalafina/QKeyMapper#1]
左侧的win 映射到左侧的ctrl  会报错 显示无效的映射

**Comment by Zalafina** [comment]
Win键在Windows下确实有点特殊，现在加在列表里也只是为了让按键列表比较完整。
稍后我会看一下，但是请不要抱希望，应该是解决不了。建议放弃用Win键映射。
如果确实看着不爽就考虑从列表里删除Win键了。毕竟全屏游戏里还有人习惯Win + D这种组合键切换回桌面。

**Comment by Zalafina** [comment]
v1.3.5 Qt6 Release的版本在Win10 22H2上测试可以正常将L-Win键映射到L-Ctrl键。基本按键动作也是正常的。是不是用的版本有点旧？

![QKeyMapper_2023-0525_16-54-31](https://github.com/Zalafina/QKeyMapper/assets/7358411/99b50be7-ff74-47e1-8b3b-c2be937c02c5)
