### ISSUE TITLE
可以映射新键盘那个copilot按键吗？

### ISSUE THREAD

**Issue by Remonli** [Zalafina/QKeyMapper#11]
我打算买新笔记本电脑，右ctl变成copilot了，这个软件能把他改回ctl吗？

因为新电脑还没买，旧电脑没那个按键，无法测试，谁能测试一下告知？

谢谢~~~

**Comment by Zalafina** [comment]
没使用过copilot键的笔记本，需要有实物测试才能知道是否支持。
但是我觉得通常这种特殊按键笔记本厂商会有自己专用的按键驱动进行调整吧，可以找找笔记本官网可下载的软件。

**Comment by Zalafina** [comment]
![Uploading image.png…]()

**Comment by Remonli** [comment]
@Zalafina 看上去应该可以映射。不过这个能不能保存到注册表，避免后台一直运行？

**Comment by Zalafina** [comment]
> @Zalafina 看上去应该可以映射。不过这个能不能保存到注册表，避免后台一直运行？

这个软件就是想要做成不修改注册表随时可以开始停止映射的动态方式，所以不能。
如果需要修改注册表的方式可以找其他软件试试，映射方式已经知道了。
