### ISSUE TITLE
请问座标点击如何映射？反复尝试一直是灰色

### ISSUE THREAD

**Issue by find-xposed-magisk** [Zalafina/QKeyMapper#12]
![image](https://github.com/user-attachments/assets/c88e6f76-38ba-4c18-8f74-6791e6875710)

**Comment by Zalafina** [comment]
![image](https://github.com/user-attachments/assets/a74da378-3e88-49cb-8724-f527f071cb46)

**Comment by Zalafina** [comment]
全屏坐标点点击应该是好用的，窗口内坐标点点击是后追加的，可能存在点问题，不是所有窗口都能生效。
全屏坐标点击可以参考下面视频。
<video id="ScreenMousePoint" src="https://github.com/user-attachments/assets/a8482c60-28ac-47bc-b029-45b3505bb400" controls="controls" width="100%" height="auto"/>

**Comment by Zalafina** [comment]
> ![image](https://private-user-images.githubusercontent.com/38677638/361240947-e2863d35-c37b-40bb-9457-f89ac4bf33df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDgzMzgsIm5iZiI6MTcyNDYwODAzOCwicGF0aCI6Ii8zODY3NzYzOC8zNjEyNDA5NDctZTI4NjNkMzUtYzM3Yi00MGJiLTk0NTctZjg5YWM0YmYzM2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjN2JkMDEwOGU2ZDY5ZGRjYWNjZGRlNDhlNWYyZDIzMWFiYzRiM2E1NGRlOTdlODkxNmNkNDY5NzAwN2I5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJ2eTk5WIGNWfjGnRuTTqwToU1iuh-trXdeQRnYofsY) 大图是这个把

是的，P站的图片。
