### ISSUE TITLE
请问如若要在SendText()括号内的字符串中包含+号时应该如何处理？

### ISSUE THREAD

**Issue by jojuniori** [Zalafina/QKeyMapper#13]
![PixPin_2024-09-15_09-06-24](https://github.com/user-attachments/assets/e4fcfd91-c0d2-41db-81b1-e886ef4455be)
如若直接写的话会被判定为连接映射按键

**Comment by Zalafina** [comment]
请尝试在主窗口的映射按键选择SendText，然后在"文本"编辑框中填写"+++"来添加，按照下面图片的添加方式供参考。
"映射项设定"窗口中的映射按键规则检查应该存在问题，之后我会在新版本中修改一下。
![image](https://github.com/user-attachments/assets/30574064-43eb-4b00-9827-f4174a840416)

**Comment by jojuniori** [comment]
😆 感谢
