### ISSUE TITLE
可否支持特定窗口使用特定策略

### ISSUE THREAD

**Issue by KunMinX** [Zalafina/QKeyMapper#14]
例如默认情况下，加载全局映射策略，特定窗口加载特定策略，
比如当前焦点进程为一般软件时，Win + W 映射到 Alt + F4，当前焦点进程为浏览器时，映射到 Ctrl + W，

**Comment by Zalafina** [comment]
> 例如默认情况下，加载全局映射策略，特定窗口加载特定策略， 比如当前焦点进程为一般软件时，Win + W 映射到 Alt + F4，当前焦点进程为浏览器时，映射到 Ctrl + W，

软件最基本的功能就是根据设定并保存好的进程名称和窗口名称来自动切换按键映射策略。
左侧的进程列表双击进程窗口后会自动将进程名和窗口名填写在"进程"和"标题"单行编辑框中，这里标题就是对应窗口名称。
点击"保存设定"按钮会将右侧的按键映射列表保存到对应进程名+窗口标题对应的设定中。
如果保存时选择了"自动匹配前台进程"勾选框，在开始映射后，如果前台窗口切换到了保存设定过的窗口名称，自动就会切换加载之前保存的按键映射列表。
全局映射对应的设定项名称"QKeyMapperGlobalSetting", 如果也勾选了"自动匹配前台进程"，则前台窗口不是保存过的设定项窗口则会自动切换到此全局映射设定内容。
所以可以给"QKeyMapperGlobalSetting"设置Win + W 映射到 Alt + F4，选择Edge浏览器进程后将Win + W 映射到 Ctrl + W，就可以实现映射策略自动切换了。
![image](https://github.com/user-attachments/assets/88caad6b-8b5b-4bb5-a921-209104a0caa8)

**Comment by KunMinX** [comment]
感谢您的解答。根据上述介绍勾选自动匹配，确实能达到甚至超出预期体验！桌面右上角会及时提示窗口变化和映射策略切换。
目前还剩最后一个问题：
若我设置 LWin to LCtrl，又为 LWin + W 单独设置 LAlt + F4，按下 LWin + W 后不关闭窗口，是因为存在叠加效果吗（Ctrl + Alt + F4），对此您有没有什么建议。

**Comment by Zalafina** [comment]
> 感谢您的解答。根据上述介绍勾选自动匹配，确实达到甚至超出预期体验！桌面右上角会及时提示窗口变化和映射策略切换。 目前还剩最后一个问题： 若我设置 LWin to LCtrl，又为 LWin + W 单独设置 LAlt + F4，按下 LWin + W 后不关闭窗口，是因为存在叠加效果吗（Ctrl + Alt + F4），对此您有没有什么建议。

如果设置了LWin to LCtrl之后，同时设置LWin + W to LAlt + F4。
此时按顺序按下LWin + W发送的按键是 L-Ctrl(L-Win) + L-Alt+F4(L-Win+W)
L-Ctrl+L-Alt+F4不会关闭窗口的原因是L-Ctrl按下状态下再按下L-Alt会改变L-Alt按键的功能，所以此时L-Alt+F4就无法进行关闭窗口的操作了。(这个通过键盘直接先按住L-Ctrl再按下L-Alt+F4按键就可以测试出来)
建议重新考虑一下要实现的需求，尝试用其他的按键映射策略来解决需求。

**Comment by KunMinX** [comment]
非常感谢解答。刚刚试了下，移除单个 Win/Ctrl 按键映射，将组合键逐个录制就没事了。
