### ISSUE TITLE
非常感谢作者大大！几乎整合了所有我想要的功能！

### ISSUE THREAD

**Issue by weixieyuzhou** [Zalafina/QKeyMapper#16]
因为游戏有需求，偶然间搜到了这个小软件。发现手柄模拟，连发这些功能都有，实在太好用了！ღ( ´･ᴗ･` )

**Comment by Zalafina** [comment]
很高兴你喜欢这个小开源软件，我自己也在每天使用并根据网友建议不断改善加入一些新功能。
