### ISSUE TITLE
这个支持DirectX的游戏窗口同步么

### ISSUE THREAD

**Issue by messnoTrace** [Zalafina/QKeyMapper#17]

**Comment by messnoTrace** [comment]
就是说，我在一个窗口移动鼠标，按键盘，同样的操作同步的发送到多个窗口，包括后台游戏窗口，我自己用postMessage的时候，DirectX 游戏窗口接受消息的时候，鼠标消息同步不过去，

**Comment by Zalafina** [comment]
![image](https://github.com/user-attachments/assets/10b6c2b1-921f-4932-b5da-278555760291)
