### ISSUE TITLE
【提示信息】这个选项似乎没有记忆功能

### ISSUE THREAD

**Issue by DarkyumeH** [Zalafina/QKeyMapper#18]
每次启动都是默认的顶部右侧，必须手动修改，但其他功能都能记住之前的选择。QT6的两个版本都试过了，是一样的。

**Comment by Zalafina** [comment]
修改提示信息位置的下拉列表选项后，点击保存设定就会保存当前的选项。
最新 QKeyMapper_v1.3.7.20241216 版本上验证没发现问题，点击保存设定后 keymapdata.ini 文件中的设定值会跟着变化，下次启动程序时候设定值与上次保存设定相同。请再验证一下。
默认值 NotificationPosition=3 是顶部右侧。
NotificationPosition=1 是顶部左侧。
![image](https://github.com/user-attachments/assets/c3a820df-92e5-4d37-8acb-0e5ca08797c1)

**Comment by DarkyumeH** [comment]
> 修改提示信息位置的下拉列表选项后，点击保存设定就会保存当前的选项。 最新 QKeyMapper_v1.3.7.20241216 版本上验证没发现问题，点击保存设定后 keymapdata.ini 文件中的设定值会跟着变化，下次启动程序时候设定值与上次保存设定相同。请再验证一下。 默认值 NotificationPosition=3 是顶部右侧。 NotificationPosition=1 是顶部左侧。 ![image](https://private-user-images.githubusercontent.com/7358411/397764829-c3a820df-92e5-4d37-8acb-0e5ca08797c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDY5ODUsIm5iZiI6MTczNDcwNjY4NSwicGF0aCI6Ii83MzU4NDExLzM5Nzc2NDgyOS1jM2E4MjBkZi05MmU1LTRkMzctOGFjYi0wZTVjYTA4Nzk3YzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjBUMTQ1ODA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUzM2YwMDQxNGExNmYyZDQxMzM2NjM3MDRmMGY1YTgwMjMyZDAzNjFiNTkzMmIwOGI1MDg3MzljMmRjODM1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RzuGa2eLmSw85TRb3igZY0OuQ-suPWMNdtHuvSrOGy4)

原来如此，由于【开机自启动】和【音效】两个选项和【提示信息】在同一界面且不需要保存设定也可以记录之前的状态，导致我以为【保存设定】仅仅是用来创建独立进程用的，设定完进程之后我就没点过了（ 实际功能并没有出问题，感谢解答。
