### ISSUE TITLE
提示缺少msvcp140_2.dll

### ISSUE THREAD

**Issue by qiufeihai** [Zalafina/QKeyMapper#2]
提示缺少msvcp140_2.dll

**Comment by Zalafina** [comment]
我在好几台Win10和Win11机器上测试时候都不需要这个文件，所以打包时候就没有加。
你是下载的1.35版本在哪个操作系统上使用的呢？ 可以先临时用下面传的附件放到软件可执行文件目录下试试看。
确实可以解决问题的话我之后打包时候加进去。
[msvcp140_2.zip](https://github.com/Zalafina/QKeyMapper/files/12104878/msvcp140_2.zip)
