### ISSUE TITLE
全键盘无冲吗？按键并发性能如何？

### ISSUE THREAD

**Issue by fanlushuai** [Zalafina/QKeyMapper#3]
技术的角度解释一下？

**Comment by Zalafina** [comment]
键盘冲突是键盘硬件决定，软件不限制。
按键并发看硬件性能，正常场景使用10个以内按键同时用手按，速度快应该也没什么问题
但同时起多个几毫秒定时器连发，我觉得Qt自己的线程队列会堆积。调用sendinput api时按串行做的。

**Comment by fanlushuai** [comment]
> 键盘冲突是键盘硬件决定，软件不限制。 按键并发看硬件性能，正常场景使用10个以内按键同时用手按，速度快应该也没什么问题 但同时起多个几毫秒定时器连发，我觉得Qt自己的线程队列会堆积。调用sendinput api时按串行做的。

ok，明白。感谢回复。
