### ISSUE TITLE
无法进行Win键映射

### ISSUE THREAD

**Issue by CharlesLiaoO** [Zalafina/QKeyMapper#4]
我无法进行win键映射（我需要映射Win+L到一个单键）

另外，这里的界面排布看不懂
![图片](https://github.com/Zalafina/QKeyMapper/assets/49112356/d627ca2b-9b5d-4d14-88e6-ecd61ae9b326)

**Comment by Zalafina** [comment]
1. Win+L是Windows的默认锁屏组合键，是要屏蔽锁屏功能？必须选这个组合键的原因是什么呢？
2. 组合键映射正常是使用原始组合键来进行组合键映射的，但是正常操作是鼠标点击焦点选到"原始组合键"编辑框后按下对应的组合键来设置按键映射，但是Win+L会执行锁屏，所以直接操作无法成功。
3. 禁用WIN键用来在一些游戏中禁止WIN键默认呼出Windows开始菜单的功能，并不是和其他功能组合使用的。
4. ">>" 勾选框用来添加顺序的按键序列，勾选后添加的映射按键可以是"A >> B >> C"这种形式，A、B、C三个按键顺序执行按下抬起。
![image](https://github.com/Zalafina/QKeyMapper/assets/7358411/abb93d45-d8a9-4d4d-ad54-04b877d50c2a)

**Comment by CharlesLiaoO** [comment]
映射Win+L的原因：
https://github.com/microsoft/PowerToys/issues/27564

我试了修改PowerToys的配置文件，能够强行映射，但有bug

**Comment by Zalafina** [comment]
想要用一个按键来映射到Win+L这种特殊用途的Windows系统组合键确实容易出现问题。
我测试了一下，只是简单的创建按键映射让一个键盘按键发送 Win+L 这种虚拟按键组合无法实现锁屏的功能，只是发送了Win+L这个虚拟按键组合，不会锁定屏幕。
我可能会尝试在下一个版本中为映射按键追加一个特定的LockScreen功能键来达到映射按键可以锁屏的功能。

**Comment by CharlesLiaoO** [comment]
啊，谢谢这么及时回复，不过，我的需求是：映射Win+L组合键到Del键。

**Comment by Zalafina** [comment]
> 啊，谢谢这么及时回复，不过，我的需求是：映射Win+L组合键到Del键。

如果只是想要单纯将Win+L组合键映射到Del键的话，左侧原始按键先选择"Del"键，右侧映射按键选"L-Win"添加。之后左侧保持"Del"键不变，右侧映射按键选"L"添加，就能够发送Win+L组合键。只是这样无法执行锁屏功能。
![image](https://github.com/Zalafina/QKeyMapper/assets/7358411/176c4842-01ce-4910-a394-325dfec80de2)
![image](https://github.com/Zalafina/QKeyMapper/assets/7358411/b9c91033-32a5-40a1-a16f-334eb30b484e)
![image](https://github.com/Zalafina/QKeyMapper/assets/7358411/4f4e2f03-7569-42e5-9fac-f37c13199fe2)

**Comment by CharlesLiaoO** [comment]
我试了，没法捕获Win+L。
我还试着找你这个程序的配置文件，企图调过按键捕获，没找到😄，你能告诉我吗？

**Comment by Zalafina** [comment]
> 我试了，没法捕获Win+L。 我还试着找你这个程序的配置文件，企图调过按键捕获，没找到😄，你能告诉我吗？

程序可执行文件的根目录下有 keymapdata.ini 文件，修改前备份一下。

**Comment by Zalafina** [comment]
最新版 v1.3.6 Build_20240221 更改了组合键映射策略，改为手动填写组合键内容，可覆盖已注册的系统组合键。
例如：原始组合键填写 "L-Win+L" ，支持按键列表参考压缩包中的 CombinationSupportKeys.txt 文件内容。
我自己测试可用，可以试验一下。

**Comment by CharlesLiaoO** [comment]
> 最新版 v1.3.6 Build_20240221 更改了组合键映射策略，改为手动填写组合键内容，可覆盖已注册的系统组合键。 例如：原始组合键填写 "L-Win+L" ，支持按键列表参考压缩包中的 CombinationSupportKeys.txt 文件内容。 我自己测试可用，可以试验一下。

感谢！我把连发按下时常改为500，基本满足了我的使用。
