### ISSUE TITLE
可以添加Fn键的映射修改吗

### ISSUE THREAD

**Issue by larphe** [Zalafina/QKeyMapper#5]

**Comment by Zalafina** [comment]
我的理解：键盘的Fn键不会向操作系统发送特定的按键码所以无法被操作系统检测到按下和抬起，所以除了键盘厂商为自己生产的键盘编写的专用驱动程序，第三方软件应该无法检测键盘的Fn键。
建议找找看你使用的键盘是否有专用的软件或驱动提供这个功能。
