### ISSUE TITLE
添加窗口化虚拟摇杆

### ISSUE THREAD

**Issue by XM666-Dev** [Zalafina/QKeyMapper#8]
![image](https://github.com/Zalafina/QKeyMapper/assets/99076011/98f260a4-1006-418e-aeb7-6b2d6e677754)

https://github.com/Zalafina/QKeyMapper/assets/99076011/25d9d955-0d70-4b3c-a2e7-a351315ed5b2

看起来vJoy-Mouse2LS/RS在一些使用摇杆瞄准的游戏中效果不是那么好。
是否可以添加类似于安卓端的虚拟摇杆，做成一个窗口显示在其他应用程序之上？
![image](https://github.com/Zalafina/QKeyMapper/assets/99076011/dc4d2483-f314-4c90-a895-bb2e0a5bcbb8)

**Comment by Zalafina** [comment]
鼠标映射虚拟摇杆本来是为了一些不支持鼠标，只支持手柄的游戏开发的功能，例如：模拟器游戏。
对于PC上同时支持键鼠和手柄的游戏，其对鼠标和摇杆操作都会进行检测，对按键映射工具的鼠标移动接收会造成影响，造成映射摇杆移动效果不佳。
这种情况通常开启多设备驱动(Interception驱动)会有所改善，因为Interception驱动的键鼠操作检测更为底层，会在游戏接收到鼠标移动操作之前拦截住，这样游戏的鼠标移动检测就不会影响到按键映射工具。
例如：暖雪 游戏里同样的设置，下面分别给出不开启多设备驱动和开启多设备驱动的视频效果。明显不开启时，鼠标映射摇杆操作无法正常使用。
<img width="1071" alt="PixPin_2024-06-02_01-15-39" src="https://github.com/Zalafina/QKeyMapper/assets/7358411/783ac72f-b95f-43cc-8826-92dc9ff75279">

不开启Interception驱动视频
https://github.com/Zalafina/QKeyMapper/assets/7358411/07067d6a-b96c-4220-b176-ac46ecb5d553

开启Interception驱动视频
https://github.com/Zalafina/QKeyMapper/assets/7358411/0a3eb963-bf9d-46af-9a31-a54477bd5317

**Comment by XM666-Dev** [comment]
我使用这个软件的目的是为了更好地支持Noita的本地联机合作模组。P1使用键鼠，P2使用手柄，因为有玩家反馈没有手柄，所以我想到使用Parsec和虚拟手柄软件来把P2用户的鼠标移动转换为手柄摇杆输入以此来实现360度瞄准射击。
开启多设备驱动后确实有所改善，但感觉还是有些不稳、不易操控，即使是在开启锁定光标的情况下。

https://github.com/Zalafina/QKeyMapper/assets/99076011/fcf59eb5-7e4a-47a5-b50b-d7b9d5e906df

**Comment by Zalafina** [comment]
开启多设备驱动 + 锁定光标 仍然效果不佳的话，只能尝试调整一下X轴和Y轴的灵敏度控制摇杆移动幅度的大小。
数值越小，摇杆移动幅度越大。
![image](https://github.com/Zalafina/QKeyMapper/assets/7358411/961de61e-19df-48d9-8455-72586e25f062)

之前对Parsec远程操作的虚拟手柄映射使用网页端手柄测试工具测试过，基本的摇杆移动是正常的，下面是B站视频参考。
https://www.bilibili.com/video/BV1xj421Z7W9/?spm_id_from=333.999.0.0&vd_source=a5d91f5ff1d5529b51b44867bba07238
