### ISSUE TITLE
Will support API detailed scheduling use?

### ISSUE THREAD

**Issue by MNDIA** [Zalafina/QKeyMapper#9]
可以支持API详细调度使用吗
以便做详细的逻辑判断：A按下时，A处于按下状态，A松开时...; 从而可以执行代码块
实现复杂高上限的功能

来自1号键盘键盘信号处理：
若B按下时A处于按下状态且LShift处于按下状态且在进程xx.exe内则
执行【不发送A/B/Shift(拦截输入)的情况下按下C】
若B松开时A处于按下状态且LShift处于按下状态且在进程xx.exe内则
执行【不发送A/B/Shift(拦截输入)的情况下松开C】

来自2号键盘的信号处理：
B按下时 执行【不发送B(拦截输入)按下C】
B松开时 执行【不发送B(拦截输入)松开C】
除了B键全部拦截

还可以配合c或python的条件和方法作为功能拓展...

**Comment by Zalafina** [comment]
没想要做成脚本类型的程序，因为AHK应该是脚本类映射的很好选择。

**Comment by MNDIA** [comment]
AHK不能区分来自不同的键盘，（区分 WM_INPUT的raw.hDevice或者键盘驱动），这是致命的。
AHK的拦截是[WH_KEYBOARD_LL](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks#wh_keyboard_ll)或
[WH_KEYBOARD](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks#wh_keyboard)级别的，只能对于按键码区分拦截，不能区分键盘。这导致使用其他驱动的输入（event.flags为0，如非SentInput输入）和物理实体键盘输入在AHK面前完全一致，这会导致映射回环。

但是InterceptionDriver对多个驱动设备的识别和拦截功能 解决了回环问题。InterceptionDriver可以根据 键盘1（物理）的驱动信号逻辑处理并完全屏蔽，只发送键盘2（虚拟）的驱动信号，在InterceptionDriver面前输入和输出信号可以由不同设备判断，没有回环问题。

目前看来QKeyMapper已经封装了足够的InterceptionDriver的功能。对于复杂高上限的功能GUI的工作量很大，但对dll留出接口调用会轻松得多

**Comment by Zalafina** [comment]
之前编写的InterceptionDriver接口调用部分都是为了QKeyMapper软件自己定制的适配内容，而且程序中大量使用了Qt库的类和方法，没有计划单独分离出dll来使用。
短时间内应该没有时间和精力做InterceptionDriver接口调用部分分离抽出dll的工作。
